### ISSUE TITLE
doc bug: suggestion of invalid Client.from_url invocation

### ISSUE THREAD

**Issue by glyph** [mithrandi/txacme#67]
https://txacme.readthedocs.io/en/latest/using.html says `client_creator` could be, "for example", `partial(Client.from_url, reactor=reactor, directory=LETSENCRYPT_STAGING_DIRECTORY, key=acme_key, alg=RS256)`.  Except `Client.from_url` doesn't take a `directory` argument, so that's an error.

**Comment by mithrandi** [comment]
It does in master. Sorry for the confusion, I need to flip the RTD versions around but I haven't done it yet.

**Comment by mithrandi** [comment]
Wait. I totally misdiagnosed this. The docs are wrong even in master.
