### ISSUE TITLE
Does it work with http2?

### ISSUE THREAD

**Issue by dholth** [mithrandi/txacme#73]
Was getting errors when `pip install Twisted[http2]`, does this work for you?

**Comment by mithrandi** [comment]
Can you provide more detail about the errors? The endpoint should "work"; http2 support will be completely disabled due to #26 / glyph/txsni#9, but I don't think you should get any errors as a result of this.

**Comment by mithrandi** [comment]
Closing this for now; if you can provide additional information I'll be happy to look into it, though.
