### ISSUE TITLE
Issuing service API for issuing a new certificate on demand

### ISSUE THREAD

**Issue by JayH5** [mithrandi/txacme#76]
It's currently only possible to add/remove certificates from txacme by touching/deleting certificate files in the certificate directory (or adding/removing from some other store implementation).

It's technically possible to directly store empty certificates in an `ICertificateStore` and then call the `AcmeIssuingService._check_certs()` but that is messy and may be prone to race conditions with the timed invocation of the same method.

It should be possible to safely add and remove certificates from txacme.

A further iteration on this is perhaps the ability to _modify_ certificates, e.g. to change (or as it is described in the certbot client, _"expand"_) the SANs (#37).

**Comment by mithrandi** [comment]
I opened #77 to cover the "remove a cert" case separately.
